### ISSUE TITLE
Can't launch Music App

### ISSUE THREAD

**Issue by Tekl** [FuzzyIdeas/MusicDecoy#2]
You write on your website, that the alternative Tool noTunes will quit the Music App. It appears that your tool does the same. When I click on the Dock icon of Apple Music, it jumps once and then the App quits. The Music-Icon also jumps once, when I press the play key. I'm running macOS 14.2 DevBeta 4.

**Comment by Tekl** [comment]
Ah, sorry. In the Readme you already mention this behaviour. What about adding a feature, that a reopen event will let Music Decoy quit, launch Music and then launch itself again? In this order, the Music.app can keep running.

**Comment by alin23** [comment]
Hi! If I do that, the second play event will also quit this app and launch Music. 

The only way is to manually quit Music Decoy and launch Music yourself. To do this in one go, you can create a macOS Shortcut that does both actions, and then add the Shortcut to the Dock.

**Comment by Tekl** [comment]
Okay, I understand. I didn't know that the play event and the reopen event are the same.

**Comment by alin23** [comment]
They are not the same, but the play event sends an `activateApp` event to whatever app is running with the `com.apple.Music` id. Launching the real Music app does the same thing.

Only launching Music Decoy again would work as that would also send a `reopen` event, but it feels non-intuitive to launch this app *again* to open the real Music app. What do you think?

**Comment by Tekl** [comment]
I think it's more intuitive than the current solution. With using the reopen event, Music Decoy could reside in the Dock. If I want to launch Apple's Music App, then I just have to click on Music Decoy.

**Comment by alin23** [comment]
I ended up relying on [a separate Shortcut](https://github.com/FuzzyIdeas/MusicDecoy#how-do-i-launch-music) for this, because in tests, people tended to launch Music Decoy twice *(like, for good measure, because what could go wrong)* when they don't see any interface show up. That makes the Music app appear and everyone is even more confused.

The Shortcut is more explicit about what should happen, and can also be added to the Dock, menubar, hotkey etc.
